FROM ubuntu:latest

RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    clang-format \
    make \
    python3 \
    build-essential \
    && apt-get clean && rm -rf /var/lib/apt/lists/*


